# PPO Training Configuration for Auto User Agent

# Environment settings
environment:
  max_conversation_length: 10
  booking_agent_config:
    config_path: "agents/chat/config.yaml"
    db_path: "database/flights.db"
    server_path: "mcp-server/database_server.py"
  verifier_config:
    config_path: "agents/verifier/config.yaml"

# Model configuration
model:
  base_model: "microsoft/DialoGPT-small"  # Smaller model for faster training
  tokenizer: "microsoft/DialoGPT-small"
  max_response_length: 30
  device: "auto"

  # Quantization settings
  use_quantization: true
  quantization_bits: 4

  # LoRA settings
  use_lora: true
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]

# PPO training hyperparameters
ppo:
  # Basic training
  learning_rate: 1.0e-5
  batch_size: 8
  mini_batch_size: 4
  gradient_accumulation_steps: 1

  # Training scale
  max_epochs: 10
  rollout_episodes: 5  # Episodes per epoch

  # PPO specific
  ppo_epochs: 4
  gamma: 0.99
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.5
  ent_coef: 0.01
  max_grad_norm: 0.5

  # Buffer settings
  use_buffer: true
  buffer_ratio: 0.3  # Ratio of buffer data to use
  adversarial_ratio: 0.3  # Ratio of adversarial examples in buffer
  buffer_size: 10000

  # Checkpointing
  save_freq: 2
  eval_freq: 1
  logging_steps: 10
  output_dir: "./ppo_training_output"

# Reward configuration
reward_system:
  # Reward weights
  verifier_weight: 0.7
  immediate_weight: 0.3

  # Length preferences
  min_response_length: 3
  max_response_length: 30
  optimal_length_range: [5, 20]

  # Penalties and bonuses
  too_short_penalty: -0.2
  too_long_penalty: -0.3
  natural_response_bonus: 0.2
  polite_ending_bonus: 0.3
  progress_reward: 0.05

# Evaluation settings
evaluation:
  num_eval_episodes: 5
  eval_objectives:
    - "I need to fly from New York to London in June 2026"
    - "Looking for business class tickets to Tokyo"
    - "Can you help me book a flight to Paris for 2 people?"
    - "I want to find the cheapest flight to Sydney"
    - "Need a direct flight from Chicago to Dubai next month"

# Logging configuration
logging:
  level: "INFO"
  log_dir: "./logs"
  tensorboard_dir: "./tensorboard_logs"
  save_conversations: true
  save_verification_reports: true

# Hardware optimization
hardware:
  mixed_precision: false  # Set to true if GPU supports it
  gradient_checkpointing: false
  num_workers: 2